name: schedule_builder
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  image_picker: ^1.0.8
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  path: any

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/blank_image.png
    - assets/thumbsup.png
